--- 
abstract: Perl interface for E-Cell Simulation Environment.
author: Kazuharu Arakawa, <gaou@sfc.keio.ac.jp>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Bio-ECell
no_index: 
  directory: 
    - inc
    - t
requires: 
  Inline::Python: 0.20
  perl: 5.6.0
version: 0.02
